name: "Install Spatialite"

inputs:
  os:
    description: "The currently running os"
    required: true

runs:
  using: "composite"
  steps:
  - name: Install spatialite (Windows)
    if: startsWith(inputs.os, 'windows')
    shell: pwsh
    run: |
      Invoke-WebRequest -Uri "https://www.7-zip.org/a/7zr.exe" -OutFile "7zr.exe"
      Invoke-WebRequest -Uri "http://www.gaia-gis.it/gaia-sins/windows-bin-amd64/mod_spatialite-5.1.0-win-amd64.7z" -OutFile "mod_spatialite.7z"
      .\7zr x mod_spatialite.7z
      mv mod_spatialite-5.1.0-win-amd64 "C:\spatialite"
      echo "C:\spatialite" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

  - name: Install spatialite (Linux)
    if: startsWith(inputs.os, 'ubuntu')
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y libsqlite3-mod-spatialite

  - name: Install spatialite (macOS)
    if: startsWith(inputs.os, 'macos')
    shell: bash
    run: |
      brew install libspatialite
