name: "Install Spatialite"

inputs:
  os:
    description: "The currently running os"
    required: true

runs:
  using: "composite"
  env:
    modspatialite-file: mod_spatialite-5.0.1-win-amd64
  steps:
    - name: Download spatialite (Windows)
      if: startsWith(inputs.os, 'windows')
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "http://www.gaia-gis.it/gaia-sins/windows-bin-amd64/${{ env.modspatialite-file }}.7z" -OutFile "mod_spatialite.7z"

    - name: Extract spatialite (Windows)
      if: startsWith(inputs.os, 'windows')
      uses: edgarrc/action-7z@v1
      with:
        args: 7z x mod_spatialite.7z

    - name: Install spatialite (Windows)
      if: startsWith(inputs.os, 'windows')
      shell: pwsh
      run: |
        mv ${{ env.modspatialite-file }} "C:\spatialite"
        echo "C:\spatialite" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install spatialite (Linux)
      if: startsWith(inputs.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-mod-spatialite
