version: 2

build:
  os: "ubuntu-24.04"
  apt_packages:
    - default-jdk
    - graphviz
  tools:
    python: "3.13"
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - models
sphinx:
  configuration: docs/source/conf.py
