from __future__ import annotations

import typing as t
from uuid import UUID

from movici_data_core.domain_model import (
    AttributeType,
    Dataset,
    DatasetFormat,
    DatasetSummary,
    DatasetType,
    EntityType,
    ModelType,
    Scenario,
    ScenarioStatus,
    Update,
    Workspace,
)
from movici_data_core.validators import ModelConfigValidator
from movici_simulation_core.types import DatasetData

T_id = t.TypeVar("T_id", str, UUID)
T_dom = t.TypeVar("T_dom")


class MoviciDataRepository(t.Protocol, t.Generic[T_id]):
    scenario_id: T_id | None

    def for_workspace(self, workspace_id: T_id | None) -> MoviciDataRepository[T_id]: ...
    def for_scenario(self, scenario_id: T_id) -> MoviciDataRepository[T_id]: ...

    @property
    def workspaces(self) -> ResourceRepository[T_id, Workspace]: ...

    @property
    def dataset_types(self) -> ResourceRepository[T_id, DatasetType]: ...

    @property
    def entity_types(self) -> ResourceRepository[T_id, EntityType]: ...

    @property
    def attribute_types(self) -> ResourceRepository[T_id, AttributeType]: ...

    @property
    def model_types(self) -> ResourceRepository[T_id, ModelType]: ...

    @property
    def datasets(self) -> DatasetRepository[T_id]: ...

    @property
    def dataset_data(self) -> DatasetDataRepository[T_id]: ...

    @property
    def scenarios(self) -> ScenarioRepository[T_id]: ...

    @property
    def updates(self) -> UpdateRepository[T_id]: ...


class ResourceRepository(t.Protocol, t.Generic[T_id, T_dom]):
    async def list(self) -> list[T_dom]: ...
    async def get_by_name(self, name: str) -> T_dom | None: ...
    async def get_by_id(self, id: T_id) -> T_dom | None: ...
    async def delete(self, id: T_id): ...
    async def create(self, obj: T_dom) -> T_id: ...
    async def update(self, id: T_id, obj: T_dom): ...
    async def exists(self, name: str) -> bool: ...


class DatasetRepository(ResourceRepository[T_id, Dataset], t.Protocol):
    async def get_summary(self, id: T_id) -> DatasetSummary: ...
    async def update_with_data(
        self, id: T_id, obj: Dataset, format: DatasetFormat, chunk_size=0
    ): ...


class DatasetDataRepository(t.Protocol, t.Generic[T_id]):  # type: ignore[misc]
    async def exists_for(self, id: T_id) -> bool: ...
    def stream_binary_data(self, id: T_id, yield_per=1) -> t.AsyncGenerator[bytes]: ...
    async def get_unstructured_data(self, id: T_id) -> dict: ...
    async def get_entity_data(self, id: T_id) -> DatasetData: ...

    async def create(self, id: T_id, data: DatasetData, format: DatasetFormat, chunk_size=0): ...
    async def delete(self, id: T_id): ...


class ScenarioRepository(t.Protocol, t.Generic[T_id]):
    def for_id(self, scenario_id: T_id) -> ScenarioRepository[T_id]: ...
    async def list(self) -> list[Scenario]: ...
    async def exists_by_name(self, name: str) -> bool: ...
    async def exists(self) -> bool: ...
    async def get_by_name(self, name: str) -> Scenario | None: ...
    async def get_by_id(self) -> Scenario | None: ...
    async def delete(self): ...
    async def create(self, obj: Scenario, validator: ModelConfigValidator) -> T_id: ...
    async def update(self, obj: Scenario, validator: ModelConfigValidator): ...
    async def set_status(self, status: ScenarioStatus): ...


class UpdateRepository(t.Protocol, t.Generic[T_id]):
    async def list(self) -> list[Update]: ...
    async def exists(self) -> bool: ...
    async def get_by_id(self, id: T_id) -> Update | None: ...
    async def create(self, obj: Update) -> T_id: ...
    async def delete_all(self): ...
