name: Pull Requests

on:
  pull_request:

env:
  python-version: "3.13"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ env.python-version }}

    - name: Set up Python
      run: uv python install

    - name: Build and install
      run: uv sync --only-dev --frozen

    - name: Run linters
      run: make lint

  test-all-platforms:
    if: contains( github.event.pull_request.labels.*.name, 'all-versions')
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Python
      run: uv python install

    - name: Install Spatialite
      uses: ./.github/actions/install-spatialite
      with:
        os: ${{ matrix.os }}

    - name: Install
      run: uv sync --group dev --frozen

    - name: Run tests
      run: |
        cd packages/simulation-core
        make test-numba

  test-numba:
    if: contains( github.event.pull_request.labels.*.name, 'numba')
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ env.python-version }}

    - name: Set up Python
      run: uv python install

    - name: Install Spatialite
      uses: ./.github/actions/install-spatialite
      with:
        os: ${{ matrix.os }}

    - name: Install
      run: uv sync --group dev --frozen

    - name: Run tests with Numba JIT enabled
      run: |
        cd packages/simulation-core
        make test-numba

  coverage:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ env.python-version }}

    - name: Set up Python
      run: uv python install

    - name: Install Spatialite
      uses: ./.github/actions/install-spatialite
      with:
        os: ${{ matrix.os }}

    - name: Install
      run: uv sync --group dev

    - name: Run tests with coverage
      run: |
        cd packages/simulation-core
        make coverage

  test-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ env.python-version }}

    - name: Set up Python
      run: uv python install

    - name: Install Spatialite
      uses: ./.github/actions/install-spatialite
      with:
        os: ubuntu-latest

    - name: Install dependencies
      run: |
          uv sync --all-groups

    - name: Test docs
      run: |
        source .venv/bin/activate
        make docs
        make doctest
